### ISSUE TITLE
BUG: ... Installation fails

### ISSUE THREAD

**Issue by IlirEdis** [open-condo-software/gitexporter#20]
The installation `npm i gitexporter` fails even if a use `--force`. attached is the whole error log file
[2023-05-30T09_04_45_659Z-debug-0.log](https://github.com/open-condo-software/gitexporter/files/11598243/2023-05-30T09_04_45_659Z-debug-0.log)

**Comment by IlirEdis** [comment]
Any news on this?
or at least more info on how to use it. Should i install it on my project or globally?
The error im getting which you see in the logs is while trying to install it in my project. 
My node -v: 18.16.0

**Comment by jcapogna** [comment]
@IlirEdis 

I had this issue on Node 18.16.0 and also Node 20.11.0

For me, it's an issue with building the`node-git` dependency. A solution is to upgrade gitexporter's `node-git` dependency to `v0.28.0-alpha.21`. 

I found an already published version of that here: https://www.npmjs.com/package/betterplace-gitexporter

**Comment by kubk** [comment]
@jcapogna The `betterplace-gitexporter` worked just fine for me, thanks!

**Comment by pahaz** [comment]
Has your problem been resolved? If not, please open a new issue. 

Please attach the result of running the command `npm install gitexporter --loglevel verbose`.
